#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to DigitalOcean's One-Click Directus Droplet. 
To keep this Droplet secure, the UFW firewall is enabled. 
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

In a web browser, you can view:
 * The Directus documentation: https://docs.directus.io
 * Your Directus installation: http://$myip
 * The Directus admin: http://$myip/admin

On the server:
 * Directus is installed at /var/www/directus/public
 * The MySQL root password is saved in /root/.digitalocean_password
 * Certbot is preinstalled. Run it to configure HTTPS. See
   http://do.co/lamp1804#enable-https for more detail.

For help and more information, visit http://docs.directus.io

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
